AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront for awesome-blog

Parameters:
  ServiceName:
    Type: String
    Default: 'awesome-blog'
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  S3BucketWebDomainName:
    Type: String
  FrontPageApiId:
    Type: String
  BackendApiId:
    Type: String

Resources:
  # ------------------------------------------------------------#
  # OAC
  # ------------------------------------------------------------#
  OAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: Access Control
        Name: OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # ------------------------------------------------------------#
  # Distribution
  # ------------------------------------------------------------#
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Join [ ' ', [ !Ref ServiceName, !Ref Environment ] ]
        Origins:
          - Id: S3
            DomainName: !Ref S3BucketWebDomainName
            OriginAccessControlId: !GetAtt OAC.Id
            S3OriginConfig:
              OriginAccessIdentity: ''
          - Id: ApiGatewayFront
            DomainName: !Sub '${FrontPageApiId}.execute-api.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
          - Id: ApiGatewayBackend
            DomainName: !Sub '${BackendApiId}.execute-api.${AWS::Region}.amazonaws.com'
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: ApiGatewayFront
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ViewerProtocolPolicy: redirect-to-https
        CacheBehaviors:
          - PathPattern: /sr/*
            TargetOriginId: S3
            Compress: true
            AllowedMethods:
              - GET
              - HEAD
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
            ViewerProtocolPolicy: redirect-to-https
          - PathPattern: /api/*
            TargetOriginId: ApiGatewayBackend
            Compress: false
            AllowedMethods:
              - GET
              - HEAD
              - OPTION
              - POST
              - PUT
              - DELETE
              - PATCH
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_200

Outputs:
  CloudFrontId:
    Value: !Ref CloudFrontDistribution
    Export:
      Name: AwesomeBlogCloudFrontId
