AWSTemplateFormatVersion: "2010-09-09"
Description: Stateful stack for awesome-blog

Parameters:
  ServiceName:
    Type: String
    Default: 'awesome-blog'
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  S3BucketWebDomainName:
    Type: String
  OpenAPISpecS3BucketName:
    Type: String
  OpenAPISpecS3Key:
    Type: String

Resources:

  # ------------------------------------------------------------#
  # API Gateway
  # ------------------------------------------------------------#
  APIGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: awesome-blog-stateful-apigateway.template.yaml
      Parameters:
        ServiceName: !Ref ServiceName
        Environment: !Ref Environment
        OpenAPISpecS3BucketName: !Ref OpenAPISpecS3BucketName
        OpenAPISpecS3Key: !Ref OpenAPISpecS3Key

  # ------------------------------------------------------------#
  # CloudFront
  # ------------------------------------------------------------#
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: awesome-blog-stateful-cloudfront.template.yaml
      Parameters:
        ServiceName: !Ref ServiceName
        Environment: !Ref Environment
        S3BucketWebDomainName: !Ref S3BucketWebDomainName
        FrontPageApiId:
          Fn::GetAtt:
            - APIGateway
            - 'Outputs.FrontPageApiId'
        BackendApiId:
          Fn::GetAtt:
            - APIGateway
            - 'Outputs.BackendApiId'

  # ------------------------------------------------------------#
  # DynamoDB
  # ------------------------------------------------------------#
  DynamoDB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: awesome-blog-stateful-dynamodb.template.yaml
      Parameters:
        ServiceName: !Ref ServiceName
        Environment: !Ref Environment


