AWSTemplateFormatVersion: "2010-09-09"
Description: APIGateway for awesome-blog

Parameters:
  ServiceName:
    Type: String
    Default: 'awesome-blog'
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  OpenAPISpecS3BucketName:
    Type: String
  OpenAPISpecS3Key:
    Type: String

Resources:
  # ------------------------------------------------------------#
  # Backend
  # ------------------------------------------------------------#
  BackendApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join [ '-', [ !Ref ServiceName, !Ref Environment, 'api' ] ]
      EndpointConfiguration:
        Types:
          - REGIONAL
      BodyS3Location:
        Bucket: !Ref OpenAPISpecS3BucketName
        Key: !Ref OpenAPISpecS3Key
      DisableExecuteApiEndpoint: true

  BackendApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref BackendApi

  BackendApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref BackendApi
      DeploymentId: !Ref BackendApiDeployment
      StageName: v1

  # ------------------------------------------------------------#
  # Frontend
  # ------------------------------------------------------------#
  FrontPageApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: HttpApiSample
      ProtocolType: HTTP

  FrontPageApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref FrontPageApi
      StageName: "$default"
      AutoDeploy: true

  FrontPageApiHelloIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref FrontPageApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Join:
          - ':'
          - - 'arn:aws:lambda'
            - !Ref AWS::Region
            - !Ref AWS::AccountId
            - 'function'
            - !Sub 'awesome-blog-${Environment}-front-page'
      PayloadFormatVersion: '2.0'
