AWSTemplateFormatVersion: "2010-09-09"
Description: APIGateway for awesome-blog

Parameters:
  ServiceName:
    Type: String
    Default: 'awesome-blog'
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd
  OpenAPISpecS3BucketName:
    Type: String
  OpenAPISpecS3Key:
    Type: String

Resources:
  # ------------------------------------------------------------#
  # Backend
  # ------------------------------------------------------------#
  BackendApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Join [ '-', [ !Ref ServiceName, !Ref Environment, 'api' ] ]
      EndpointConfiguration:
        Types:
          - REGIONAL
      BodyS3Location:
        Bucket: !Ref OpenAPISpecS3BucketName
        Key: !Ref OpenAPISpecS3Key
      DisableExecuteApiEndpoint: true

  BackendApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref BackendApi
      StageName: v1

  # ------------------------------------------------------------#
  # Frontend
  # ------------------------------------------------------------#
  FrontPageApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: !Join [ '-', [ !Ref ServiceName, !Ref Environment, 'front' ] ]
      ProtocolType: HTTP

  FrontPageApiDefaultStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref FrontPageApi
      StageName: "$default"
      AutoDeploy: true

  FrontPageApiLambdaIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref FrontPageApi
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Join:
          - ':'
          - - 'arn:aws:lambda'
            - !Ref AWS::Region
            - !Ref AWS::AccountId
            - 'function'
            - !Sub 'awesome-blog-${Environment}-front-page'
            - 'live'
      PayloadFormatVersion: '2.0'

  FrontPageApiLambdaIntegrationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::Join:
          - ':'
          - - 'arn:aws:lambda'
            - !Ref AWS::Region
            - !Ref AWS::AccountId
            - 'function'
            - !Sub 'awesome-blog-${Environment}-front-page'
            - 'live'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${FrontPageApi}/*/*"

  FrontPageApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref FrontPageApi
      RouteKey: GET /{proxy+}
      AuthorizationType: NONE
      Target: !Sub "integrations/${FrontPageApiLambdaIntegration}"

Outputs:
  BackendApiId:
    Value: !Ref BackendApi
  FrontPageApiId:
    Value: !Ref FrontPageApi
  FrontEndApiEndpoint:
    Value: !GetAtt FrontPageApi.ApiEndpoint
