name: Lint
on:
  workflow_call:

jobs:
  lint-cfn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install cfn-lint
        run: |
          python -m pip install --upgrade pip
          pip install cfn-lint

      - name: Add problem matcher
        run: echo "::add-matcher::.github/cfn-lint-matcher.json"

      - name: Lint by cfn-lint
        run: cfn-lint ./cfn/template/*.yaml -f parseable -i W3002

  lint-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-actionlint@v1

      - name: Check workflow files
        shell: bash
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
