name: Trigger test
on:
  push:
    branches:
      - 'main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      template-version: ${{ steps.TemplateVersion.outputs.template-version }}
      s3-bucket: ${{ steps.upload.outputs.s3-bucket }}
      s3-bucket-prefix: ${{ steps.upload.outputs.s3-bucket-prefix }}
    steps:
      - id: TemplateVersion
        name: TemplateVersion
        run: echo "template-version=v$(date +"%Y%m%d%H%M")" >> "$GITHUB_OUTPUT"

      - id: ArtifactBucket
        run: |
          S3_BUCKET="awesome-cmn-cfn"
          S3_BUCKET_PREFIX="${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}/${{ steps.TemplateVersion.outputs.template-version }}"
          {
            echo "s3-bucket=${S3_BUCKET}"
            echo "s3-bucket-prefix=${S3_BUCKET_PREFIX}"
          } >> "$GITHUB_OUTPUT"

  lint:
    uses: ./.github/workflows/_lint.yaml

  upload-cloudformation-template:
    needs:
      - lint
      - prepare
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        template-name:
          - 'awesome-blog-s3.template.yaml'
          - 'awesome-blog-stateful.template.yaml'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ap-northeast-1

      - id: upload
        name: Upload Cloudformation Template
        run: |
          OUTPUT_TEMPLATE_FILE="./cfn/out/${{ matrix.template-name }}"

          aws cloudformation package \
            --template-file ./cfn/template/${{ matrix.template-name }} \
            --s3-bucket ${{ needs.prepare.outputs.s3-bucket }} \
            --s3-prefix ${{ needs.prepare.outputs.s3-bucket-prefix }} \
            --output-template-file "${OUTPUT_TEMPLATE_FILE}"

          echo "output-template-file=${OUTPUT_TEMPLATE_FILE}" >> "$GITHUB_OUTPUT"

      - name: Validate
        run: |
          aws cloudformation validate-template \
            --template-body file://./${{ steps.upload.outputs.output-template-file }}

      - name: Upload Packaged Template
        run: |
          aws s3 cp \
            ${{ steps.upload.outputs.output-template-file }} \
            s3://${{ needs.prepare.outputs.s3-bucket }}/${{ needs.prepare.outputs.s3-bucket-prefix }}/

  upload-openapi-spec:
    needs:
      - lint
      - prepare
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE_ARN }}
          aws-region: ap-northeast-1

      - id: upload-api-spec
        name: Upload OpenAPI Specification
        working-directory: ./openapi
        run: |
          for env in dev stg prd
          do
            mkdir $env
            for name in `find . -maxdepth 1 -type f -name '*.yaml'`; do sed -e "s/awesome-blog-dev/awesome-blog-$env/g" $name > ./$env/$name; done
          done

          aws s3 cp \
            . \
            s3://${{ needs.prepare.outputs.s3-bucket }}/${{ needs.prepare.outputs.s3-bucket-prefix }}/openapi/ \
            --recursive

  tag:
    needs:
      - upload-cloudformation-template
      - upload-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.OWNER_PAT }}

      - id: Tag
        name: Push Tag
        run: |
          git tag ${{ needs.prepare.outputs.template-version}}
          git push origin ${{ needs.prepare.outputs.template-version}}
